version: '3'
services:
    papermc:
        build: 
            context: .
        container_name: papermc
        environment:
            - EULA=true
        ports:
            - 25565:25565
        volumes: 
            - ./data:/minecraft/data
            - ./plugins:/minecraft/plugins
