name: Update minecraft

on:
  schedule:
    - cron: '0 0 * * *'
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Download versions manifest
      uses: wei/curl@v1
      with:
        args: -fsSL 'https://papermc.io/api/v2/projects/paper' --output version.json
    - name: Load version
      id: load-papcermc-version
      run: |
          content=`cat version.json`
          latest_version=`echo $(jq -r '.versions' | last <<< "$content")`
          echo $latest_version
