name: Update minecraft

on:
  schedule:
    - cron: '0 0 * * *'
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest version
      id: latest-version
      run: |
           echo "::set-output name=LATEST_VERSION::$(curl -sS https://papermc.io/api/v2/projects/paper | jq .versions | sed 's/\"//g')"
           echo {{ $LATEST_VERSION }}
